"""Write a dvc.yaml for an experiment whose run already exists.

Rule 4 wants a `dvc.yaml` per experiment and a committed `dvc.lock`.  For a run
that is already done, the stage is adopted rather than executed: write the file,
then `dvc commit -f <target>`, which records the output on disk as the stage's
output without running anything.

The stages come from the decks beside the experiment.  A deck named <name>.fds
declares CHID <name>, and its outputs live in FDS/cases/<name>/.  Only decks
whose case directory actually exists are emitted -- several experiment
directories hold decks for scratch runs whose output was never kept, and the
case directory is usually named differently for those.  Only output files that
are present are listed.

    python3 make_pipeline.py experiments/01_baseline_garden [...]

Outs are tracked where FDS writes them.  The .s3d volumes are marked
`cache: false`: outputs DVC knows about but never copies or pushes.
"""
import os, sys

_d = os.path.dirname(os.path.abspath(__file__))
while not os.path.isfile(os.path.join(_d, "paths.py")):
    _d = os.path.dirname(_d)
sys.path.insert(0, _d)
from paths import FDS_ROOT, REPO  # noqa: E402

CACHED = ["_1.prt5", "_1_1.bf", "_1_2.bf", "_1_1.sf", "_1_2.sf"]
UNCACHED = ["_1_1.s3d", "_1_2.s3d", "_1_3.s3d"]
HAND_WRITTEN = ("07_wick3_house_ignition", "12_no_ladder_tree",
                "13_ladder_tree_pair")


def outputs(chid):
    """The output files that exist for this case, cached and uncached."""
    case = os.path.join(FDS_ROOT, "cases", chid)
    cached = [chid + s for s in CACHED
              if os.path.exists(os.path.join(case, chid + s))]
    uncached = [chid + s for s in UNCACHED
                if os.path.exists(os.path.join(case, chid + s))]
    smv = [chid + ".smv"] if os.path.exists(os.path.join(case, chid + ".smv")) else []
    return cached + smv, uncached


def emit(exp_rel, decks):
    """Build the dvc.yaml text for one experiment."""
    lines = [
        "# Generated by scripts/make_pipeline.py -- edit that, not this file.",
        "# The stage is adopted, not run: `dvc commit -f` records the output that",
        "# already exists.  `dvc repro` reproduces it for real.",
        "stages:",
        "  solve:",
        "    foreach:",
    ]
    for deck in decks:
        lines.append("      %s:" % deck[:-4])
        lines.append("        dir: %s" % exp_rel)
    lines += ["    do:", "      wdir: ../..", "      cmd: >-",
              "        python3 scripts/run_fds.py ${item.dir}/${key}.fds --threads 4",
              "        && python3 scripts/strip_terrain.py FDS/cases/${key} ${key}",
              "      deps:",
              "        - ${item.dir}/${key}.fds",
              "        - scripts/run_fds.py",
              "        - scripts/strip_terrain.py",
              "      outs:"]
    # Output names follow the case, so they template off ${key}.  A file is
    # only listed if every deck in the experiment has one, or one stage
    # instance would claim a file belonging to another.
    present = [set(outputs(d[:-4])[0]) for d in decks]
    present_u = [set(outputs(d[:-4])[1]) for d in decks]
    for suffix in CACHED + [".smv"]:
        if all(any(f.endswith(suffix) for f in s) for s in present):
            lines.append("        - FDS/cases/${key}/${key}%s" % suffix)
    for suffix in UNCACHED:
        if all(any(f.endswith(suffix) for f in s) for s in present_u):
            lines.append("        - FDS/cases/${key}/${key}%s:" % suffix)
            lines.append("            cache: false")
    return "\n".join(lines) + "\n"


def main():
    for exp in sys.argv[1:]:
        exp = os.path.abspath(exp)
        name = os.path.basename(exp)
        if name in HAND_WRITTEN:
            print("%-32s hand-written, skipped" % name)
            continue
        decks = sorted(f for f in os.listdir(exp) if f.endswith(".fds"))
        decks = [d for d in decks
                 if os.path.isdir(os.path.join(FDS_ROOT, "cases", d[:-4]))]
        if not decks:
            print("%-32s no case directory, skipped" % name)
            continue
        text = emit(os.path.relpath(exp, REPO), decks)
        open(os.path.join(exp, "dvc.yaml"), "w").write(text)
        print("%-32s %d deck(s), %d lines" % (name, len(decks), text.count("\n")))


if __name__ == "__main__":
    main()
